file_format: "1"
id: vindom
name: Vindom
type: shield
url: https://github.com/MakotoKurauchi/vindom
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - vindom_left
  - vindom_right
